Computer Vision

In [1]:
import cv2 
import numpy as np

Discrete Convolution Function

In [2]:
# 2D Convolution, assuming padding = 0
def convolution_2D(image, kernel):

  image_size_i = int(image.shape[0])
  image_size_j = int(image.shape[1])
  kernel_size_i = int(kernel.shape[0])
  kernel_size_j = int(kernel.shape[1])

  output_size_i = image_size_i - kernel_size_i + 1
  output_size_j = image_size_j - kernel_size_j + 1
  output = np.zeros((output_size_i, output_size_j))

  for i in range(image_size_i):
    for j in range(image_size_j):
      if i > image_size_i - kernel_size_i or j > image_size_j - kernel_size_j:
        continue
      else:
        output[i,j] = (kernel * image[i: i + kernel_size_i, j: j + kernel_size_j]).sum()
  return output

In [3]:
Gx_kernel = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
Gy_kernel = np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
print(Gx_kernel)
print(Gy_kernel)

[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]
[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]


In [4]:
# Use convolution_2D to calculate Gx, Gy, gradient magnitude, gradient angle, and edge angle of the Sobel Operator
def Sobel_Operator(image):
  Gx_kernel = np.array([[-1,0,1],[-2,0,2],[-1,0,1]])
  Gy_kernel = np.array([[1,2,1],[0,0,0],[-1,-2,-1]])
  Gx = convolution_2D(image, Gx_kernel)
  Gy = convolution_2D(image, Gy_kernel)
  print("Gx matrix is \n", Gx)
  print("Gy matrixis \n", Gy)
  gradient_magnitude = np.sqrt(np.power(Gx, 2) + np.power(Gy, 2))
  print("Gradient magnitude matrix is \n", gradient_magnitude)
  gradient_angle = np.arctan2(Gy, Gx) * 180 / np.pi
  print("Gradient angle matrix is (degrees)\n", gradient_angle)
  edge_angle = gradient_angle + 90
  print("Edge Angle matrix is (degrees)\n", edge_angle)

In [5]:
# Test on the Sobel Operator
image = np.array([[120,125,212,239],[90,105,180,200],[85,198,200,210],[75,212,260,195]])
Sobel_Operator(image)

Gx matrix is 
 [[387. 316.]
 [505. 102.]]
Gy matrixis 
 [[ -99.  -20.]
 [-279. -262.]]
Gradient magnitude matrix is 
 [[399.46213838 316.63227883]
 [576.9454047  281.15476165]]
Gradient angle matrix is (degrees)
 [[-14.34933204  -3.6214847 ]
 [-28.91956379 -68.72839108]]
Edge Angle matrix is (degrees)
 [[75.65066796 86.3785153 ]
 [61.08043621 21.27160892]]
